### PR TITLE
Update to version 3.32

### PR DESCRIPTION
**Pull request by Zlopez**
Signed-off-by: Michal Konecny <michal.konecny@packetseekers.eu>

### CODE REVIEW

**Comment by nedrichards** [comment]
arg, do we have an org.gnome.chess vs org.gnome.Chess issue ;-)

**Comment by Zlopez** [comment]
@nedrichards 
Yes, we have, but I renamed it and still have issue.

**Comment by Zlopez** [comment]
Hm, I tried the build and got `Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown`

**Comment by Zlopez** [comment]
@nedrichards 
According to @mcatanzaro this issue could be related to the name of the flatpak `org.gnome.chess` vs `org.gnome.Chess`. So it looks like I'm unable to update it till the flatpak could be renamed, for this see https://github.com/flathub/flathub/issues/227

**Comment by Zlopez** [comment]
Repository was renamed, there is no need for this PR anymore.

**Pull request closed without merging**
