### PR TITLE
Update gnuchess

### PR DESCRIPTION
**Pull request by AsciiWolf**
I originally tried to update stockfish as well, but any newer version than 11 did not compile.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
screenshot

Tested and seems to work fine. Also, the upstream Flatpak manifest [already has](https://gitlab.gnome.org/GNOME/gnome-chess/-/blob/main/org.gnome.Chess.json?ref_type=heads#L23) the same gnuchess version.

/cc @mcatanzaro

By the way, we may consider adding x-checker-data for gnuchess.

**Comment by Zlopez** [comment]
> I originally tried to update stockfish as well, but any newer version than 11 did not compile.

I found out about that when updating gnome runtime. Every newer version needs something downloaded from network to be even able to compile, which is not great and I don't want to allow it.

**Comment by Zlopez** [comment]
One think I noticed as well is that there is no option anymore in the application to choose the AI of opponent. I remember there was some kind of dropdown in settings or when starting new game.

**Review by Zlopez — APPROVED** [review]

**Comment by Zlopez** [comment]
`x-data-checker` is not a bad addition for the gnuchess. Feel free to create a PR for it or fill an issue.

**Comment by AsciiWolf** [comment]
> > I originally tried to update stockfish as well, but any newer version than 11 did not compile.
> 
> I found out about that when updating gnome runtime. Every newer version needs something downloaded from network to be even able to compile, which is not great and I don't want to allow it.

That's not the only problem. Recent versions also fail with some LTO related error and disabling LTO via cxxflag does not fix that error.

**Comment by mcatanzaro** [comment]
I would just remove Stockfish. I'm sure these problems are fixable, but it's not particularly valuable to have a bunch of different unbeatable chess engines to play against.

Using `x-data-checker` sounds great.

**Pull request merged**
